global:
  scrape_interval: 5s

scrape_configs:
  # - job_name: 'model-metrics'
  #   metrics_path: /model-metrics  # your GET endpoint
  #   static_configs:
  #     - targets: ['metrics-server:8000']
  
  - job_name: 'inference-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inference-api:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "/etc/prometheus/alert_rules.yml"

