services:
  mlflow_postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflow_db
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflowpass
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mlflow_net

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO console
    volumes:
      - ./minio_data:/data
    networks:
      - airflow_net
    # entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]


  mlflow:
    build: .
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - mlflow_postgres
      - minio
    networks:
      - airflow_net
      - mlflow_net

networks:
  airflow_net:
    external: true
  mlflow_net:
    driver: bridge
